runtime: python311
entrypoint: gunicorn -b :$PORT app:app --timeout 120
instance_class: F1

env_variables:
  PLAYWRIGHT_BROWSERS_PATH: /tmp/playwright
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "1"
  PLAYWRIGHT_SKIP_VALIDATION: "1"

handlers:
- url: /.*
  script: auto

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  target_throughput_utilization: 0.6 